name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache toolchain
        uses: actions/cache@v3
        id: cache-toolchain
        with:
          path: ~/x-tools/arm-ev3-linux-gnueabi
          key: toolchain-sources-v1-${{ hashFiles('cross.config') }}
          
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gperf bison flex texinfo help2man gawk libtool-bin automake build-essential qemu-user-static
          echo "${HOME}/x-tools/arm-ev3-linux-gnueabi/bin" >> $GITHUB_PATH
          
      - name: Install crosstool-NG
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        run: |
          wget http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.27.0.tar.xz
          tar xf crosstool-ng-1.27.0.tar.xz
          cd crosstool-ng-1.27.0
          ./configure --prefix=/opt/crosstool-ng
          make -j$(nproc)
          sudo make install
          echo "/opt/crosstool-ng/bin" >> $GITHUB_PATH
          
      - name: Build toolchain
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/cross-toolchain
          cp cross.config ~/cross-toolchain/.config
          cd ~/cross-toolchain
          ct-ng build -j$(nproc)
      
      - name: Clean up disk space
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        run: |
          sudo apt-get clean
          sudo apt-get autoremove -y
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf $HOME/.cache
          docker system prune -af || true
          df -h

      - name: Build packages
        run: |
          chmod +x full.sh
          ./full.sh -a -o
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Packages
          path: |
            /home/runner/cross-compile/packages/*.deb

      - name: Create Release and upload packages
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}-${{ github.run_number }}
          name: Build #${{ github.run_number }}
          body: |
            Automated build of packages
            - Built from commit: ${{ github.sha }}
          files: /home/runner/cross-compile/packages/*.deb
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
